id: IB54A3152
legacy_id: P007136
ocr_import_info:
  bdrc_scan_id: W23177
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T00:56:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T00:58:05.592337+00:00'
last_modified: 2022-09-02 08:58:15.749204
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23177
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23177
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཆོས་དགོངས་པ་གཅིག་པའི་གསལ་བྱེད།
  author: ཞྭ་དམར ༠༤་པ་ཆོས་གྲགས་ཡེ་ཤེས།
statistics:
  ocr_word_mean_confidence_index: 0.7940460593598684
  ocr_word_median_confidence_index: 0.9300000071525574
quality: null
bases:
  I0381:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0381
      total_pages: 364
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0381.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.7940460593598684
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
