id: IB54A3152
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T00:58:56+00:00'
last_modified: '2022-06-09T06:23:06.380746+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23177
  title: དམ་ཆོས་དགོངས་པ་གཅིག་པའི་གསལ་བྱེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9C22:
      image_group_id: I0381
      title: ''
      total_pages: 364
      order: 1
      base_file: 9C22.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
