id: P007136
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-17 12:44:01.641309
source_metadata:
  id: bdr:W23177
  title: དམ་ཆོས་དགོངས་པ་གཅིག་པའི་གསལ་བྱེད
  author: ''
  volumes:
    48501e3813344270bdc37f901015c9f9:
      image_group_id: I0381
      title: ''
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
